The compiler used for execution of the program is :- gcc compiler
The executable file created is :- nsettipa_HW2.c

%.o: %.c %.h  Makefile
	${COMPILER} $< -c 

clean:
	rm -f *.o *~ ${EXES} ${CFILES}


